version: "3.8"
name: gosip

services:
  gosip:
    image: gosip
    build: .
    container_name: gosip
    ports:
      - "4412:4412"
    restart: unless-stopped
    environment:
      CTF_FLAG: ${RCTF_FLAG}
    networks:
      - gosip-net

networks:
  gosip-net:
    internal: false
    driver: bridge
