name: gosip

services:
  gosip:
    build: .
    container_name: gosip
    ports:
      - "4412:4412"
    restart: unless-stopped
    environment:
      CTF_FLAGS: ${RCTF_FLAG}
    networks:
      - gosip-net

networks:
  sign-up-net:
    internal: false
    driver: bridge
