version: "3.8"
name: google-fetcher
services:
  web:
    image: google-fetcher-web
    build: ./web
    ports:
      - "8080:8080"
    networks:
      - google-fetcher-net

  backend:
    image: google-fetcher-backend
    build: ./backend
    environment:
      CTF_FLAGS: ${RCTF_FLAGS}

    networks:
      - google-fetcher-net

networks:
  google-fetcher-net:
    internal: false
    driver: bridge
