services:
  sign-up:
    image: sign-up
    environment:
      CTF_FLAG: ${RCTF_FLAG}
    networks:
      - sign-up-net
    expose:
      - "4411"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    cpus: 0.5
    pids_limit: 50

networks:
  sign-up-net:
    internal: false
    driver: bridge