version: "3.8"
name: sign-up

services:
  sign-up:
    image: sign-up
    build: .
    container_name: sign-up
    environment:
      CTF_FLAG: ${RCTF_FLAG}
    ports:
      - "4411:4411"
    restart: unless-stopped
    networks:
      - sign-up-net

networks:
  sign-up-net:
    internal: false
    driver: bridge