services:
  welcome-to-hcs:
    image: welcome-to-hcs
    environment:
      CTF_FLAG: ${RCTF_FLAG}
    networks:
      - welcome-to-hcs-net
    expose:
      - "4413"
    read_only: false
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    cpus: 0.5
    pids_limit: 50

networks:
  welcome-to-hcs-net:
    internal: false
    driver: bridge
