name: ape

services:
  web:
    image: ape-web
    build: .
    ports:
      - "5555:5555"
    environment:
      - FLAG=${RCTF_FLAG:-}
    networks:
      - ape
networks:
  ape:
    internal: false
    driver: bridge
